version: '3.9'

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no      
    ports:
      - '8081:8080'
    networks:
      - spark-net
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark-net
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyspark
    environment:
      - GRANT_SUDO=yes
      - NB_UID=1000
      - NB_GID=1000
      - PYTHON_VERSION=3.8
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
    networks:
      - spark-net

networks:
  spark-net:
