version: '3.9'

services:
  pyspark-notebook:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./imports:/home/jovyan/work
    environment:
      - SPARK_OPTS=--master=local[*]
      - JUPYTER_TOKEN=easy
